package maingui;

import gameassets.Constants;
import gameassets.Globals;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;

public class HighScoreScreen extends javax.swing.JFrame implements ScreenInitializer {

    private static HighScoreScreen highScoreScreen = null;

    /**
     * Creates new form HighScore
     */

    private HighScoreScreen() {
        initComponents();
        addRows();
    }

    public static HighScoreScreen getInstance() {
        if (highScoreScreen == null) {
            highScoreScreen = new HighScoreScreen();
            highScoreScreen.setVisible(true);
        }
        return highScoreScreen;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        highScoreTable = new javax.swing.JTable() {
            public boolean editCellAt(int row, int column, java.util.EventObject e) {
                return false;
            }
        };
        howToPlay = new javax.swing.JLabel();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("High Scores");
        setPreferredSize(new java.awt.Dimension(500, 600));
        setResizable(false);
        setIconImage(Constants.GAME_ICON);

        jPanel1.setBackground(Constants.DARK);
        jPanel1.setForeground(Constants.LIGHT);

        jScrollPane1.setForeground(Constants.LIGHT);
        jScrollPane1.setFocusable(false);

        highScoreTable.setBackground(Constants.DARK);
        highScoreTable.setFont(new java.awt.Font("Cambria Math", Font.PLAIN, 14)); // NOI18N
        highScoreTable.setForeground(Constants.LIGHT);

        highScoreTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                        "Date", "Name", "Duration", "High Score"
                }
        ));
        highScoreTable.setGridColor(new java.awt.Color(60, 60, 60));
        highScoreTable.setRowHeight(30);
        highScoreTable.setRowMargin(5);
        highScoreTable.setAutoCreateRowSorter(true);
        highScoreTable.setRowSelectionAllowed(false);
        highScoreTable.setSelectionBackground(Constants.LIGHT);
        highScoreTable.setSelectionForeground(Constants.DARK);
        highScoreTable.getTableHeader().setResizingAllowed(true);
        highScoreTable.getTableHeader().setReorderingAllowed(false);
        highScoreTable.setUpdateSelectionOnSort(true);
        jScrollPane1.setViewportView(highScoreTable);

        howToPlay.setBackground(Constants.DARK);
        howToPlay.setFont(mainFont(50, Font.BOLD));
        howToPlay.setForeground(Constants.LIGHT);
        howToPlay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        howToPlay.setText("High Scores");
        howToPlay.setFocusable(false);
        howToPlay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        howToPlay.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                                .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(howToPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(110, 110, 110))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(howToPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void addRows() {
        DefaultTableModel model = (DefaultTableModel) highScoreTable.getModel();
        Globals.readPlayersData().forEach(s -> model.addRow((Object[]) s));
    }

    // Variables declaration - do not modify
    public javax.swing.JTable highScoreTable;
    private javax.swing.JLabel howToPlay;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration
}
