package maingui;

import gameassets.Constants;

import javax.swing.*;
import java.awt.*;
import java.nio.file.Files;
import java.nio.file.Paths;

public class InstructionsScreen extends javax.swing.JFrame implements ScreenInitializer {

    private static InstructionsScreen instructionsScreen = null;


    /**
     * Creates new form Instructions
     */

    private InstructionsScreen() {
        initComponents();
    }

    public static InstructionsScreen getInstance() {
        if (instructionsScreen == null) {
            instructionsScreen = new InstructionsScreen();
            instructionsScreen.setVisible(true);
        }
        return instructionsScreen;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        howToPlay = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        instructionsText = new javax.swing.JTextArea();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("How To Play");
        setBackground(Constants.DARK);
        setResizable(false);
        setLocationRelativeTo(null);
        setIconImage(Constants.GAME_ICON);

        jPanel1.setBackground(Constants.DARK);
        jPanel1.setForeground(Constants.LIGHT);

        howToPlay.setBackground(Constants.DARK);
        howToPlay.setFont(mainFont(50, Font.BOLD));
        howToPlay.setForeground(Constants.LIGHT);
        howToPlay.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        howToPlay.setText("How To Play");
        howToPlay.setFocusable(false);
        howToPlay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        howToPlay.setRequestFocusEnabled(false);

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setFocusable(false);

        instructionsText.setEditable(false);
        instructionsText.setBackground(Constants.DARK);
        instructionsText.setColumns(20);
        instructionsText.setFont(new java.awt.Font("Cambria Math", Font.PLAIN, 18)); // NOI18N
        instructionsText.setForeground(Constants.LIGHT);
        instructionsText.setRows(5);
        instructionsText.setTabSize(2);
        try {
            instructionsText.setText(new String(Files.readAllBytes(Paths.get(Constants.ASSETS_DIR + "Instructions.txt"))));
        } catch (Exception e) {
            System.err.println(e.getMessage());
        }
        instructionsText.setAutoscrolls(false);
        instructionsText.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        instructionsText.setFocusable(false);
        instructionsText.setRequestFocusEnabled(false);
        instructionsText.setSelectedTextColor(Constants.DARK);
        instructionsText.setSelectionColor(Constants.LIGHT);
        instructionsText.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(instructionsText);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(166, 166, 166)
                                                .addComponent(howToPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(25, 25, 25)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(howToPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    // Variables declaration - do not modify
    private javax.swing.JLabel howToPlay;
    private javax.swing.JTextArea instructionsText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration
}
