package maingui;

import gameassets.Constants;
import gameassets.Globals;

import javax.swing.*;
import java.awt.*;

public class SinglePlayerScreen extends javax.swing.JFrame implements ScreenInitializer {

    private static SinglePlayerScreen singlePlayerScreen = null;

    /**
     * Creates new form SinglePlayer
     */


    private SinglePlayerScreen() {
        initComponents();
    }

    public static SinglePlayerScreen getInstance() {
        if (singlePlayerScreen == null) {
            singlePlayerScreen = new SinglePlayerScreen();
            singlePlayerScreen.setVisible(true);
        }
        return singlePlayerScreen;
    }

    public void removeInstance() {
        singlePlayerScreen = null;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        singlePlayerField = new javax.swing.JTextField();
        startGame = new javax.swing.JButton();
        mediumLevel = new javax.swing.JLabel();
        yourNameLabel = new javax.swing.JLabel();
        levelsSlider = new javax.swing.JSlider();
        levels = new javax.swing.JLabel();
        hardLevel = new javax.swing.JLabel();
        easyLevel = new javax.swing.JLabel();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Single Player");
        setFocusable(false);
        setPreferredSize(new java.awt.Dimension(500, 400));
        setResizable(false);
        setLocationRelativeTo(null);
        setIconImage(Constants.GAME_ICON);

        jPanel1.setBackground(Constants.DARK);
        jPanel1.setForeground(Constants.LIGHT);
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 400));

        singlePlayerField.setBackground(Constants.LIGHT);
        singlePlayerField.setFont(mainFont(25, Font.PLAIN));
        singlePlayerField.setForeground(Constants.DARK);
        singlePlayerField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        singlePlayerField.setText("Name");
        singlePlayerField.setBorder(null);
        singlePlayerField.setPreferredSize(new java.awt.Dimension(300, 70));
        singlePlayerField.setSelectedTextColor(Constants.LIGHT);
        singlePlayerField.setSelectionColor(Constants.DARK);

        startGame.setBackground(Constants.LIGHT);
        startGame.setFont(mainFont(50, Font.BOLD));
        startGame.setForeground(Constants.DARK);
        startGame.setText("Start");
        startGame.setBorder(null);
        startGame.setBorderPainted(false);
        startGame.setFocusPainted(false);
        startGame.setFocusable(false);
        startGame.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        startGame.setPreferredSize(new java.awt.Dimension(200, 70));
        startGame.setRequestFocusEnabled(false);
        startGame.addActionListener(this::startGameActionPerformed);

        mediumLevel.setBackground(Constants.DARK);
        mediumLevel.setFont(mainFont(20, Font.PLAIN));
        mediumLevel.setForeground(Constants.LIGHT);
        mediumLevel.setText("medium");
        mediumLevel.setFocusable(false);
        mediumLevel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        mediumLevel.setRequestFocusEnabled(false);

        yourNameLabel.setBackground(Constants.DARK);
        yourNameLabel.setFont(mainFont(35, Font.BOLD));
        yourNameLabel.setForeground(Constants.LIGHT);
        yourNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yourNameLabel.setText("Your Name");
        yourNameLabel.setFocusable(false);
        yourNameLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        yourNameLabel.setRequestFocusEnabled(false);

        levelsSlider.setBackground(Constants.DARK);
        levelsSlider.setForeground(Constants.LIGHT);
        levelsSlider.setMaximum(3);
        levelsSlider.setMinimum(1);
        levelsSlider.setValue(2);
        levelsSlider.setFocusable(false);
        levelsSlider.addChangeListener(e -> levelStateChanged());

        levels.setBackground(Constants.DARK);
        levels.setFont(mainFont(35, Font.BOLD));
        levels.setForeground(Constants.LIGHT);
        levels.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        levels.setText("Level");
        levels.setFocusable(false);
        levels.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        levels.setRequestFocusEnabled(false);

        hardLevel.setBackground(Constants.DARK);
        hardLevel.setFont(mainFont(20, Font.PLAIN));
        hardLevel.setForeground(Constants.LIGHT);
        hardLevel.setText("hard");
        hardLevel.setFocusable(false);
        hardLevel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        hardLevel.setRequestFocusEnabled(false);

        easyLevel.setBackground(Constants.DARK);
        easyLevel.setFont(mainFont(20, Font.PLAIN));
        easyLevel.setForeground(Constants.LIGHT);
        easyLevel.setText("easy");
        easyLevel.setFocusable(false);
        easyLevel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        easyLevel.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(singlePlayerField, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(yourNameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(3, 3, 3)
                                                .addComponent(easyLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(mediumLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(hardLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(levels, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(levelsSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(43, 43, 43))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(startGame, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(160, 160, 160))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(levels, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(levelsSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(easyLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(mediumLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(hardLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(yourNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(singlePlayerField, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(6, 6, 6)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                                .addComponent(startGame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void startGameActionPerformed(java.awt.event.ActionEvent evt) {
        Globals.firstPlayer.name = singlePlayerField.getText();
        if (!Globals.firstPlayer.name.equals("")) {
            buttonSound.play(false);
            dispose();

            Globals.startGame();
        }
    }

    private void levelStateChanged() {
        switch (levelsSlider.getValue()) {
            case 1 -> Globals.gameLevel = Constants.LEVELS.EASY;
            case 3 -> Globals.gameLevel = Constants.LEVELS.HARD;
            default -> Globals.gameLevel = Constants.LEVELS.MEDIUM;
        }
    }


    // Variables declaration - do not modify
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSlider levelsSlider;
    private javax.swing.JLabel mediumLevel;
    private javax.swing.JLabel levels;
    private javax.swing.JLabel hardLevel;
    private javax.swing.JLabel easyLevel;
    private javax.swing.JButton startGame;
    private javax.swing.JTextField singlePlayerField;
    private javax.swing.JLabel yourNameLabel;
    // End of variables declaration
}
