package maingui;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import gameassets.Constants;
import gameassets.PlayAudio;

import javax.swing.*;
import java.awt.*;

public class StartScreen extends javax.swing.JFrame implements ScreenInitializer {

    /**
     * Creates new form MainInterface
     */

    private final PlayAudio musicLoop;

    public StartScreen(PlayAudio musicLoop) {
        this.musicLoop = musicLoop;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    public void initComponents() {

        mainPanel = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        singlePlayButton = new javax.swing.JButton();
        highScoreButton = new javax.swing.JButton();
        instructionsButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        muteButton = new javax.swing.JButton();
        slogan = new javax.swing.JLabel();
        multiPlayerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Air Hockey Game");
        setBackground(Constants.DARK);
        setForeground(Constants.LIGHT);
        setPreferredSize(new java.awt.Dimension(600, 800));
        setResizable(false);
        ImageIcon icon = new ImageIcon(Constants.IMAGE_DIR + "air-hockey.png");
        setIconImage(icon.getImage());

        mainPanel.setBackground(Constants.DARK);
        mainPanel.setForeground(Constants.LIGHT);
        mainPanel.setPreferredSize(new java.awt.Dimension(600, 800));

        logo.setBackground(Constants.DARK);
        logo.setFont(mainFont(30, Font.PLAIN));
        logo.setForeground(Constants.LIGHT);
        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setText("An enjoyable game powered with an AI");
        logo.setFocusable(false);
        logo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        logo.setRequestFocusEnabled(false);

        singlePlayButton.setBackground(Constants.LIGHT);
        singlePlayButton.setFont(mainFont(50, Font.BOLD));
        singlePlayButton.setForeground(Constants.DARK);
        singlePlayButton.setText("Single");
        singlePlayButton.setBorder(null);
        singlePlayButton.setBorderPainted(false);
        singlePlayButton.setFocusPainted(false);
        singlePlayButton.setFocusable(false);
        singlePlayButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        singlePlayButton.setPreferredSize(new java.awt.Dimension(150, 70));
        singlePlayButton.setRequestFocusEnabled(false);
        singlePlayButton.addActionListener(this::buttonActionPerformed);

        highScoreButton.setBackground(Constants.LIGHT);
        highScoreButton.setFont(mainFont(50, Font.BOLD));
        highScoreButton.setForeground(Constants.DARK);
        highScoreButton.setText("High Score");
        highScoreButton.setBorder(null);
        highScoreButton.setBorderPainted(false);
        highScoreButton.setFocusPainted(false);
        highScoreButton.setFocusable(false);
        highScoreButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        highScoreButton.setPreferredSize(new java.awt.Dimension(300, 70));
        highScoreButton.setRequestFocusEnabled(false);
        highScoreButton.addActionListener(this::buttonActionPerformed);

        instructionsButton.setBackground(Constants.LIGHT);
        instructionsButton.setFont(mainFont(50, Font.BOLD));
        instructionsButton.setForeground(Constants.DARK);
        instructionsButton.setText("How To Play");
        instructionsButton.setBorder(null);
        instructionsButton.setBorderPainted(false);
        instructionsButton.setFocusPainted(false);
        instructionsButton.setFocusable(false);
        instructionsButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        instructionsButton.setPreferredSize(new java.awt.Dimension(300, 70));
        instructionsButton.setRequestFocusEnabled(false);
        instructionsButton.setRolloverEnabled(false);
        instructionsButton.setVerifyInputWhenFocusTarget(false);
        instructionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });

        exitButton.setBackground(Constants.LIGHT);
        exitButton.setFont(mainFont(50, Font.BOLD));
        exitButton.setForeground(Constants.DARK);
        exitButton.setText("Exit");
        exitButton.setBorder(null);
        exitButton.setBorderPainted(false);
        exitButton.setFocusPainted(false);
        exitButton.setFocusable(false);
        exitButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exitButton.setPreferredSize(new java.awt.Dimension(150, 70));
        exitButton.setRequestFocusEnabled(false);
        exitButton.addActionListener(this::buttonActionPerformed);

        muteButton.setActionCommand("Mute");
        muteButton.setBackground(null);
//        muteButton.setForeground(Constants.DARK);
        muteButton.setIcon(new javax.swing.ImageIcon(Constants.IMAGE_DIR + "volume.png"));
        muteButton.setBorder(null);
        muteButton.setBorderPainted(false);
        muteButton.setFocusable(false);
        muteButton.setRequestFocusEnabled(false);
        muteButton.addActionListener(this::buttonActionPerformed);

        slogan.setBackground(Constants.DARK);
        slogan.setFont(mainFont(75, Font.BOLD));
        slogan.setForeground(Constants.LIGHT);
        slogan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        slogan.setText("Air Hockey");
        slogan.setFocusable(false);
        slogan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        slogan.setRequestFocusEnabled(false);

        multiPlayerButton.setBackground(Constants.LIGHT);
        multiPlayerButton.setFont(mainFont(50, Font.BOLD));
        multiPlayerButton.setForeground(Constants.DARK);
        multiPlayerButton.setText("Two");
        multiPlayerButton.setBorder(null);
        multiPlayerButton.setBorderPainted(false);
        multiPlayerButton.setFocusPainted(false);
        multiPlayerButton.setFocusable(false);
        multiPlayerButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        multiPlayerButton.setPreferredSize(new java.awt.Dimension(150, 70));
        multiPlayerButton.setRequestFocusEnabled(false);
        multiPlayerButton.addActionListener(this::buttonActionPerformed);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
                mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                                .addContainerGap(71, Short.MAX_VALUE)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                                .addComponent(muteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(23, 23, 23))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(209, 209, 209))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(60, 60, 60))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                                                .addComponent(singlePlayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(multiPlayerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(highScoreButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(instructionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                                                .addGap(137, 137, 137))))
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                        .addContainerGap(130, Short.MAX_VALUE)
                                        .addComponent(slogan, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(104, 104, 104)))
        );
        mainPanelLayout.setVerticalGroup(
                mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                                .addContainerGap(146, Short.MAX_VALUE)
                                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(singlePlayButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(multiPlayerButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(51, 51, 51)
                                .addComponent(highScoreButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(mainPanelLayout.createSequentialGroup()
                                                .addGap(53, 53, 53)
                                                .addComponent(instructionsButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(41, 41, 41)
                                                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap())
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                                                .addGap(237, 237, 237)
                                                .addComponent(muteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(78, 78, 78))))
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(slogan, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(651, Short.MAX_VALUE)))
        );

        logo.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {
        String action = evt.getActionCommand();
        switch (action) {
            case "Single":
                buttonSound.play(false);
                SinglePlayerScreen sPlayer = new SinglePlayerScreen();
                sPlayer.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                sPlayer.setVisible(true);
                break;
            case "Two":
                buttonSound.play(false);
                TwoPlayerScreen tPlayer = new TwoPlayerScreen();
                tPlayer.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                tPlayer.setVisible(true);
                break;
            case "High Score":
                buttonSound.play(false);
                HighScoreScreen highScore = new HighScoreScreen();
                highScore.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                highScore.setVisible(true);
                break;
            case "How To Play":
                buttonSound.play(false);
                InstructionsScreen ins = new InstructionsScreen();
                ins.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                ins.setVisible(true);
                break;
            case "Mute":
                if (musicLoop.isMuted) {
                    musicLoop.resume();
                    muteButton.setIcon(new javax.swing.ImageIcon(Constants.IMAGE_DIR + "volume.png"));
                } else {
                    musicLoop.stop();
                    muteButton.setIcon(new javax.swing.ImageIcon(Constants.IMAGE_DIR + "mute.png"));
                }
                break;
            case "Exit":
                buttonSound.play(false);
                musicLoop.close();
                this.dispose();
        }
    }


    // Variables declaration - do not modify
    private javax.swing.JButton exitButton;
    private javax.swing.JButton highScoreButton;
    private javax.swing.JButton instructionsButton;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel slogan;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton multiPlayerButton;
    private javax.swing.JButton muteButton;
    private javax.swing.JButton singlePlayButton;
    // End of variables declaration
}
